# Generated by Django 6.0.2 on 2026-03-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['faculty', 'course']},
        ),
        migrations.RenameField(
            model_name='program',
            old_name='name',
            new_name='course',
        ),
        migrations.AddField(
            model_name='program',
            name='faculty',
            field=models.CharField(choices=[('FoCIT', 'Faculty of Computing and Information Technology'), ('FAMECO', 'Faculty of Media and Economics'), ('FoET', 'Faculty of Engineering and Technology'), ('FoBE', 'Faculty of Business and Economics'), ('FoST', 'Faculty of Science and Technology'), ('FoSST', 'Faculty of Social Sciences and Technology')], default='FoCIT', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('course', 'faculty')},
        ),
    ]
