# Generated by Django 6.0.2 on 2026-03-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_program_options_rename_name_program_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='duration_years',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='unit',
            name='year',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
