# Generated by Django 6.0.2 on 2026-03-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_program_duration_years_unit_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['year', 'semester', 'unit_code']},
        ),
        migrations.AddField(
            model_name='session',
            name='radius_metres',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
