# Generated by Django 6.0.2 on 2026-03-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_unit_options_session_radius_metres'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='current_semester',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='current_year',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
