# Generated by Django 6.0.2 on 2026-03-24 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_lecturer',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='teacher',
        ),
        migrations.AddField(
            model_name='unit',
            name='lecturer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_lecturer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_units', to=settings.AUTH_USER_MODEL),
        ),
    ]
