# Generated by Django 6.0.2 on 2026-04-27 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_webauthnchallenge_webauthncredential'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webauthnchallenge',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='webauthncredential',
            name='aaguid',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='webauthnchallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webauthncredential',
            name='credential_id',
            field=models.TextField(unique=True),
        ),
    ]
